import argparse
import csv
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np


def _safe_float(raw: str) -> float | None:
    if raw is None:
        return None
    text = raw.strip()
    if not text:
        return None
    try:
        return float(text)
    except ValueError:
        return None


def _load_rows(path: Path) -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    with path.open("r", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            rows.append(row)
    return rows


def _device_kind(device: str) -> str | None:
    normalized = device.strip().lower()
    if normalized.startswith("cpu"):
        return "cpu"
    if normalized.startswith("cuda"):
        return "gpu"
    return None


def _aggregate_by_algorithm_device(
    rows: list[dict[str, str]],
    reward_metric: str,
) -> dict[str, dict[str, dict[str, float]]]:
    grouped: dict[str, dict[str, dict[str, list[float]]]] = {}

    for row in rows:
        algorithm = (row.get("algorithm") or "").strip().lower()
        device = (row.get("device") or "").strip()
        kind = _device_kind(device)
        if not algorithm or kind is None:
            continue

        duration = _safe_float(row.get("duration_seconds", ""))
        fps = _safe_float(row.get("frames_per_second", ""))
        reward = _safe_float(row.get(reward_metric, ""))

        bucket = grouped.setdefault(algorithm, {}).setdefault(
            kind,
            {
                "duration_seconds": [],
                "frames_per_second": [],
                "reward": [],
            },
        )
        if duration is not None:
            bucket["duration_seconds"].append(duration)
        if fps is not None:
            bucket["frames_per_second"].append(fps)
        if reward is not None:
            bucket["reward"].append(reward)

    result: dict[str, dict[str, dict[str, float]]] = {}
    for algorithm, by_device in grouped.items():
        result[algorithm] = {}
        for kind, metrics in by_device.items():
            result[algorithm][kind] = {
                "duration_seconds": float(np.mean(metrics["duration_seconds"]))
                if metrics["duration_seconds"]
                else float("nan"),
                "frames_per_second": float(np.mean(metrics["frames_per_second"]))
                if metrics["frames_per_second"]
                else float("nan"),
                "reward": float(np.mean(metrics["reward"]))
                if metrics["reward"]
                else float("nan"),
            }
    return result


def _speedup_ratio(cpu_metrics: dict[str, float], gpu_metrics: dict[str, float]) -> float:
    gpu_fps = gpu_metrics.get("frames_per_second", float("nan"))
    cpu_fps = cpu_metrics.get("frames_per_second", float("nan"))
    if np.isfinite(gpu_fps) and np.isfinite(cpu_fps) and cpu_fps > 0.0:
        return gpu_fps / cpu_fps

    cpu_duration = cpu_metrics.get("duration_seconds", float("nan"))
    gpu_duration = gpu_metrics.get("duration_seconds", float("nan"))
    if np.isfinite(cpu_duration) and np.isfinite(gpu_duration) and gpu_duration > 0.0:
        return cpu_duration / gpu_duration

    return float("nan")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Plot GPU/CPU speedup and reward comparison from benchmark summary CSV."
    )
    parser.add_argument(
        "--summary-csv",
        type=Path,
        default=Path("benchmarl_setup") / "runs" / "benchmark_summary.csv",
        help="Path to benchmark summary CSV generated by run_benchmark.py.",
    )
    parser.add_argument(
        "--reward-metric",
        choices=["tail_mean_reward", "final_reward", "best_reward"],
        default="tail_mean_reward",
        help="Reward metric used in the CPU vs GPU comparison subplot.",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("benchmarl_setup") / "runs" / "cpu_gpu_summary_comparison.png",
        help="Output PNG path.",
    )
    parser.add_argument(
        "--title",
        type=str,
        default="CPU vs GPU Benchmark Summary",
        help="Figure title.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if not args.summary_csv.exists():
        raise FileNotFoundError(f"Summary CSV not found: {args.summary_csv}")

    rows = _load_rows(args.summary_csv)
    aggregated = _aggregate_by_algorithm_device(rows, reward_metric=args.reward_metric)

    algorithms = sorted(
        algorithm
        for algorithm, by_device in aggregated.items()
        if "cpu" in by_device and "gpu" in by_device
    )
    if not algorithms:
        raise ValueError(
            "No algorithm has both CPU and GPU rows in the summary CSV. "
            "Run a benchmark with --devices cpu,cuda first."
        )

    speedups = []
    cpu_rewards = []
    gpu_rewards = []
    for algorithm in algorithms:
        cpu_metrics = aggregated[algorithm]["cpu"]
        gpu_metrics = aggregated[algorithm]["gpu"]
        speedups.append(_speedup_ratio(cpu_metrics, gpu_metrics))
        cpu_rewards.append(cpu_metrics["reward"])
        gpu_rewards.append(gpu_metrics["reward"])

    args.out.parent.mkdir(parents=True, exist_ok=True)

    x = np.arange(len(algorithms), dtype=float)
    fig, axes = plt.subplots(1, 2, figsize=(12, 5))

    # Speedup chart: > 1.0 means GPU faster.
    ax0 = axes[0]
    bars = ax0.bar(x, speedups, width=0.6, color="#2d8f5a", alpha=0.9)
    ax0.axhline(1.0, color="#555555", linestyle="--", linewidth=1)
    ax0.set_xticks(x)
    ax0.set_xticklabels([a.upper() for a in algorithms])
    ax0.set_ylabel("GPU / CPU speedup")
    ax0.set_title("Training Speedup")
    ax0.grid(True, axis="y", alpha=0.25)
    for bar, value in zip(bars, speedups):
        if np.isfinite(value):
            ax0.text(
                bar.get_x() + bar.get_width() / 2,
                value,
                f"{value:.2f}x",
                ha="center",
                va="bottom",
                fontsize=9,
            )

    # Reward comparison chart.
    ax1 = axes[1]
    width = 0.34
    ax1.bar(x - width / 2, cpu_rewards, width=width, label="CPU", color="#4c72b0")
    ax1.bar(x + width / 2, gpu_rewards, width=width, label="GPU", color="#dd8452")
    ax1.set_xticks(x)
    ax1.set_xticklabels([a.upper() for a in algorithms])
    ax1.set_ylabel(args.reward_metric)
    ax1.set_title("Reward Comparison")
    ax1.grid(True, axis="y", alpha=0.25)
    ax1.legend()

    fig.suptitle(args.title)
    fig.tight_layout()
    fig.savefig(args.out, dpi=150)

    print(f"Loaded rows: {len(rows)}")
    print(f"Algorithms compared: {', '.join(algorithm.upper() for algorithm in algorithms)}")
    print(f"Reward metric: {args.reward_metric}")
    print(f"Saved: {args.out}")


if __name__ == "__main__":
    main()